2025-10-12 01:17:48.363 +0330 [83278] LOG:  starting PostgreSQL 17.6 on x86_64-pc-linux-gnu, compiled by clang version 19.1.7, 64-bit
2025-10-12 01:17:48.363 +0330 [83278] LOG:  listening on IPv6 address "::1", port 5432
2025-10-12 01:17:48.363 +0330 [83278] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2025-10-12 01:17:48.365 +0330 [83278] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
2025-10-12 01:17:48.369 +0330 [83281] LOG:  database system was shut down at 2025-10-12 01:17:37 +0330
2025-10-12 01:17:48.374 +0330 [83278] LOG:  database system is ready to accept connections
2025-10-12 01:18:23.988 +0330 [83645] ERROR:  permission denied for schema public at character 14
2025-10-12 01:18:23.988 +0330 [83645] STATEMENT:  CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL)
2025-10-12 01:19:26.551 +0330 [83852] FATAL:  role "postgres" does not exist
2025-10-12 01:19:35.286 +0330 [83918] FATAL:  database "winder" does not exist
2025-10-12 01:22:48.368 +0330 [83279] LOG:  checkpoint starting: time
2025-10-12 01:24:33.733 +0330 [83279] LOG:  checkpoint complete: wrote 1055 buffers (6.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=105.190 s, sync=0.156 s, total=105.365 s; sync files=447, longest=0.043 s, average=0.001 s; distance=5192 kB, estimate=5192 kB; lsn=0/1A060B0, redo lsn=0/19FEF50
2025-10-12 01:32:48.733 +0330 [83279] LOG:  checkpoint starting: time
2025-10-12 01:32:52.092 +0330 [83279] LOG:  checkpoint complete: wrote 34 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.307 s, sync=0.036 s, total=3.359 s; sync files=19, longest=0.013 s, average=0.002 s; distance=35 kB, estimate=4677 kB; lsn=0/1A07F98, redo lsn=0/1A07F08
